# Generated by Django 3.0.8 on 2020-07-25 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveSmallIntegerField(help_text='итого')),
                ('quantity', models.PositiveSmallIntegerField(default=1, help_text='кол-во')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Время завершения сделки', null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='items.Item')),
            ],
            options={
                'ordering': ['customer'],
            },
        ),
    ]
