# Generated by Django 3.0.8 on 2020-07-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=50)),
                ('cost', models.IntegerField(default=100, help_text='Цена', null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
